[target.aarch64-unknown-linux-gnu.dockerfile]
file = "./Dockerfile.aarch64-unknown-linux-gnu"
context = "."

[build.env]
passthrough = [
    "SLINT_NO_QT",
    "SLINT_STYLE=fluent",
    "SLINT_TEST_FILTER",
    "SLINT_INTERPRETER_ERROR_WHITELIST",
]
