import { FontWeights } from "../singletons/style.slint";

export component DemoMenuButton inherits Text {
    in-out property <bool> selected: false;
    callback clicked();

    height: self.font-size * 1.5;

    color: white;
    font-weight: FontWeights.light;
    font-size: 25px;
    horizontal-alignment: TextHorizontalAlignment.center;
    text: "DemoButton";
    vertical-alignment: TextVerticalAlignment.center;

    TouchArea {
        width: parent.width;
        height: parent.height;
        clicked => {
            parent.clicked();
        }
    }
}
