import { HorizontalBox, ProgressIndicator } from "std-widgets.slint";
import { Label } from "../widgets/label.slint";

export component HwInfoWidget inherits HorizontalBox {
    in-out property <string> text: "text";
    in-out property <int> value: 42;
    in-out property <float> progress: 0.5;

    Text {
        text: root.text;
        vertical-alignment: center;
    }

    Label {
        text: root.value;
    }

    ProgressIndicator {
        progress: root.progress;
    }
}