import { KDControlStyle } from "../singletons/style.slint";

export component KDButton inherits Rectangle {
    in-out property <bool> dark-theme: KDControlStyle.dark-theme;
    callback clicked <=> touch.clicked;

    width: 180px;
    height: 60px;

    background := Rectangle {
        width: root.width;
        height: root.height;

        left := Image {
            x: parent.x;
            source: touch.pressed
                ? root.dark-theme ? @image-url("../resources/button_rect_left_dark_pressed.png") : @image-url("../resources/button_rect_left_pressed.png")
                : root.dark-theme ? @image-url("../resources/button_rect_left_dark.png") : @image-url("../resources/button_rect_left.png");
        }
        mid := Image {
            x: left.x + left.width;
            width: root.width - left.width - right.width;
            height: root.height;

            image-fit: ImageFit.fill;
            source: touch.pressed
                ? root.dark-theme ? @image-url("../resources/button_rect_mid_dark_pressed.png") : @image-url("../resources/button_rect_mid_pressed.png")
                : root.dark-theme ? @image-url("../resources/button_rect_mid_dark.png") : @image-url("../resources/button_rect_mid.png");
        }
        right := Image {
            x: mid.x + mid.width;
            source: touch.pressed
                ? root.dark-theme ? @image-url("../resources/button_rect_right_dark_pressed.png") : @image-url("../resources/button_rect_right_pressed.png")
                : root.dark-theme ? @image-url("../resources/button_rect_right_dark.png") : @image-url("../resources/button_rect_right.png");
        }
    }

    touch := TouchArea {}
}
