import { Palette, BorderSpec, Images, LayoutSpec, Typography } from "../kdab/styling.slint";
import { SlintText } from "../kdab/slint-text.slint";

export component Progress {
    in property <int> minimum: 0;
    in property <int> maximum: 100;
    in-out property <int> value;

    property <float> range: root.maximum - root.minimum;
    property <float> progress: (root.value - root.minimum) / root.range;
    property <length> value-position: root.progress * root.width; 

    height: 22px;
 
    track := Rectangle {
        width: 100%;
        height: 10px;
        border-radius: self.height / 2;
        border-width: BorderSpec.default-width;
        border-color: Palette.border;
        background: Palette.background;
        opacity: 0.5;
    }
          
    Rectangle {
        x: 0;
        width: root.value-position;
        height: track.height;
        border-radius: track.border-radius;
        border-width: BorderSpec.default-width;
        border-color: Palette.border;
        background: Palette.background;
    }

    function set_value(value: int) {
        if root.value == value {
            return;
        }

        root.value = max(root.minimum, min(root.maximum, value));
    }
}
