import { CheckBox, VerticalBox, GridBox, HorizontalBox, TextEdit } from "std-widgets.slint";

// Widgets
import { DemoMenu } from "widgets/demo_menu.slint";
import { DemoView } from "widgets/demo_view.slint";
import { KdabDemoPage } from "pages/kdab_demo_page.slint";
import { SystemResourcesTile } from "components/app/system_info_tile.slint";
import { TextView } from "widgets/text_view.slint";

// Singletons
import { ChargerInterface, RoboInterface, EnergyMonitorInterface, IndustrialInterface, SystemResourcesData } from "singletons/demo_interface.slint";
import { DemoLoader } from "singletons/demo_loader.slint";
import { FontWeights } from "singletons/style.slint";

// Exports
export { ChargerInterface, DemoLoader, EnergyMonitorInterface, RoboInterface, IndustrialInterface, SystemResourcesData }

export component AppWindow inherits Window {
    property <length> border: 90px;

    width: 1920px;
    height: 1080px;
    // no-frame: true;

    background-image := Image {
        property <length> content-rect-x: 669px;
        property <length> content-rect-y: 242px;
        property <length> content-rect-width: 1156px;
        property <length> content-rect-height: 715px;

        source: @image-url("resources/background.png");
        // z: 10;
    }

    menu-bar := DemoMenu {
        x: background-image.content-rect-x;
        y: 155px;

        width: background-image.content-rect-width;

        alignment: LayoutAlignment.stretch;
    }

    side-bar := GridLayout {
        property <length> horizontal-margin: (system-resources-tile.width - demo-description.width) / 2;

        x: root.border - horizontal-margin;
        y: 200px;

        height: 813px;

        spacing: 20px;

        demo-title := Text {
            col: 1;
            row: 0;

            color: white;
            font-weight: FontWeights.light;
            font-size: 25px;
            text: DemoLoader.demo-title;

            horizontal-alignment: TextHorizontalAlignment.left;
            vertical-alignment: TextVerticalAlignment.center;
        }

        demo-description := TextView {
            col: 1;
            row: 1;

            width: 450px;

            font-size: 20px;
            text: DemoLoader.demo-description;
            text-color: white;
        }

        system-resources-tile := SystemResourcesTile {
            col: 0;
            row: 2;
            colspan: 3;

            width: 530px;

            animate height {
                duration: 400ms;
                easing: ease-out-back;
            }
        }
    }

    demo-view := DemoView {
        x: background-image.content-rect-x;
        y: background-image.content-rect-y;
        z: -1;

        width: background-image.content-rect-width;
        height: background-image.content-rect-height;

        demo-index: DemoLoader.selected-index;
    }
}
