export component AppWindow inherits Window {
    in-out property <bool> move-rectangles: false;

    width: 1920px;
    height: 1080px;

    Rectangle {
        x: root.move-rectangles ? root.width - self.width : 0;
        y: 0px;
        width: 40px;
        height: 40px;
        background: blue;
        animate x {
            duration: 5000ms;
            easing: linear;
        }
    }

    Rectangle {
        x: root.move-rectangles ? 0 : root.width - self.width;
        y: root.height - self.height;
        width: 40px;
        height: 40px;
        background: blue;
        animate x {
            duration: 5000ms;
            easing: linear;
        }
    }
}
