import "../../../resources/fonts/SourceCodePro-Variable.ttf";

export global Palette {
//     property <color> slint-blue: #3586f4;
    // out property <color> background: #ffffff;
//     out property <color> foreground: #000000;
    out property <color> border: #234770ff;
    // out property <color> text-black: #000000ff;
    // out property <color> text-blue: #0b5fd1ff;
//     out property <color> selected-border: #0084ff;
//     out property <color> disabled-border: #8bb2e7;
//     out property <color> selection-background: slint-blue;
//     out property <color> selection-foreground: #ffffff;
//     out property <brush> gradient: @linear-gradient(180deg, white 0%, #f4f9ff 80%, #f4f9ff 100%);
//     out property <brush> popup-background: #f9fbff;
//     out property <color> selected-backround: #f7f7f7;
//     out property <color> item-selected-background: #cde1fd9e;

//     out property <color> unchecked-background: #e5e5e5;
//     out property <color> unchecked-thumb: #f5f9ff;
//     out property <color> checked-background: #cde1fd;
//     out property <color> checked-thumb: white;
}

export global Typography {
    out property <string> default-font-family: font-family-regular;
    out property <length> default-font-size: font-size-normal;
    out property <color> default-color: #ffffff;

    // out property <string> font-family-light: "Open Sans Light";
    out property <string> font-family-regular: "Source Code Pro";
    // out property <string> font-family-bold: "Open Sans Bold";

    out property <length> font-size-small: 15px;
    out property <length> font-size-normal: 20px;
    out property <length> font-size-large: 24px;
    out property <length> font-size-larger: 42px;
}

// export global BorderSpec {
//     out property <length> default-width: 2px;
//     out property <length> input-border-radius: 18px;
// }

// export global LayoutSpec {
//     out property <length> default-padding: 18px;
//     out property <length> small-padding: 8px;
//     out property <length> default-spacing: 8px;
// }

// export global Icons {
//     out property <image> clear-icon: @image-url("../../assets/clear-icon.svg");
//     out property <image> dropdown-open: @image-url("../../assets/dropdown-open.svg");
//     out property <image> dropdown-closed: @image-url("../../assets/dropdown-closed.svg");
// }

export global Images {
    out property <image> section-icon-1: @image-url("../../../resources/demos/industrial/number-1.png");
    out property <image> section-icon-2: @image-url("../../../resources/demos/industrial/number-2.png");
}
